apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo6
  name: todo6
  namespace: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo6
  strategy: {}
  template:
    metadata:
      labels:
        app: todo6
    spec:
      containers:
      - image: murilobeltrame/todo:net-6
        name: todo
        resources: {}
status: {}