apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo7
  name: todo7
  namespace: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo7
  strategy: {}
  template:
    metadata:
      labels:
        app: todo7
    spec:
      containers:
      - image: murilobeltrame/todo:net-7
        name: todo
        resources: {}
status: {}